# Generated by Django 3.1.2 on 2020-11-16 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kuzaneli', '0002_picture_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='vorh',
            field=models.CharField(choices=[('V', 'Vertical'), ('H', 'Horizontal')], default=None, max_length=1),
        ),
    ]
