# Generated by Django 3.1.2 on 2020-12-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kuzaneli', '0003_picture_vorh'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='cart',
            field=models.BooleanField(default=False),
        ),
    ]
