# Generated by Django 3.1.2 on 2020-12-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kuzaneli', '0004_picture_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='title',
            field=models.CharField(db_column='name', max_length=64),
        ),
    ]
